# Generated by Django 5.2.5 on 2025-08-29 10:21

import django.db.models.deletion
import guardsys.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[guardsys.documents.models.validate_file_size])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.guardedobject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('object', 'original_name'), name='uq_document_object_filename')],
            },
        ),
    ]
