version: '3.9'

services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=file:./data/dev.db
      - PORT=4000
      - PUBLIC_URL=http://localhost:5173
    volumes:
      - server_data:/app/data
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  server_data: