# Generated by Django 5.2.5 on 2025-08-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('MONTHLY', 'Ежемесячно'), ('QUARTERLY', 'Ежеквартально'), ('CUSTOM', 'Кастом')], default='MONTHLY', max_length=16)),
                ('interval_days', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_done_at', models.DateField(blank=True, null=True)),
                ('next_due_at', models.DateField()),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.guardedobject')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='maintenance.periodicitytemplate')),
            ],
        ),
    ]
