# Generated by Django 5.2.5 on 2025-08-29 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=32, verbose_name='КПП')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('entity', models.CharField(choices=[('USER', 'Пользователь'), ('ORGANIZATION', 'Организация'), ('OBJECT', 'Объект'), ('MAINTENANCE', 'ТО'), ('DOCUMENT', 'Документ')], max_length=32)),
                ('entity_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GuardedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('equipment', models.TextField(verbose_name='Оборудование')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('ARCHIVED', 'В архиве')], default='ACTIVE', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deputy_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_objects', to=settings.AUTH_USER_MODEL)),
                ('main_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_objects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='core.organization')),
            ],
        ),
    ]
